package ex03_scores;
/*
 *  학생 10명의 Java 중간고사 점수를 입력하여 평균과 평균 이상인 점수의 학생 수 구하기
 *
 *   스타일 1: 반복문 사용하지 않고서 작성하기
 *   이 프로그램은 프로그램 생성 프로그램인 Ex4_8_5_ScoresAverage_GeneratingProgram.java을 통해 자동적으로 만들어진 프로그램임
 */
public class Ex4_1_2_ScoresAverage10_AutoGenerated {
    static final int NOOFSTUDENTS = 10; // 총 학생수를 저장하는 상수변수

    public static void main(String[] args)  {
        int  score1, score2, score3, score4, score5, score6, score7, score8, score9, score10;  // 점수들을 저장할 변수들

        int sumOfScore = 0;     // 점수 합계를 저장할 변수, 반드시 0으로 초기화해야 함

        // 10명의 학생 점수를 입력하고 이를 누적시킴

        System.out.print("\n\n  ** 10명의 학생 점수를 입력하하여 합과 평균 구하기 **\n\n");

        System.out.print("  * input score 1 > ");
        score1 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score1;

        System.out.print("  * input score 2 > ");
        score2 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score2;

        System.out.print("  * input score 3 > ");
        score3 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score3;

        System.out.print("  * input score 4 > ");
        score4 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score4;

        System.out.print("  * input score 5 > ");
        score5 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score5;

        System.out.print("  * input score 6 > ");
        score6 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score6;

        System.out.print("  * input score 7 > ");
        score7 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score7;

        System.out.print("  * input score 8 > ");
        score8 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score8;

        System.out.print("  * input score 9 > ");
        score9 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score9;

        System.out.print("  * input score 10 > ");
        score10 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score10;

        double avgOfScore;              // 점수 평균 저장 변수
        avgOfScore = sumOfScore / (double) NOOFSTUDENTS;  // 실수 평균을 구하기 위해 NOOFSTUDENTS를 실수로 나누어야 함

        int noGTavg = 0;                // 평균보다 높은 점수 학생수 저장 변수
        if (score1 >= avgOfScore) noGTavg++;     // 1번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score2 >= avgOfScore) noGTavg++;     // 2번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score3 >= avgOfScore) noGTavg++;     // 3번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score4 >= avgOfScore) noGTavg++;     // 4번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score5 >= avgOfScore) noGTavg++;     // 5번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score6 >= avgOfScore) noGTavg++;     // 6번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score7 >= avgOfScore) noGTavg++;     // 7번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score8 >= avgOfScore) noGTavg++;     // 8번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score9 >= avgOfScore) noGTavg++;     // 9번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score10 >= avgOfScore) noGTavg++;     // 10번째 점수가 평균보다 크면 noGTavg 1 증가시킴 

        System.out.println();
        System.out.println("\n  ** 학생 점수 현황 **   \n");
        System.out.println("  * 총 학생수 = " + NOOFSTUDENTS);
        System.out.println("  * " + NOOFSTUDENTS + " 학생 점수 합 = " + sumOfScore);
        System.out.println("  * " + NOOFSTUDENTS + " 학생 점수 평균 = " + avgOfScore);
        System.out.println("  * 평균보다 높은 점수 학생 수 = " + noGTavg);
    }
}
