package ex12_more;
/*
 *  [ ScoresAverage_GeneratingProgram ] :
 *      주어진 학생수만큼의 점수를 입력하여 평균보다 큰 점수의 학생수를 풀력하는 프로그램을 생성하는 프로그램
 *  
 *    o 이 프로그램은 프로그램을 생성하는 프로그램이다. 
 *      - 프로그램을 생성한다는 것은 "프로그램은 단순히 문자들의 나열"이라는 것을   확인시키는 것이며, 
 *        System.out.println() 메소드에서 Java 클래스를 구성하는  문자들을 출력하면 된다.  
 *    
 *      - 이러한 프로그래밍 기법은 Java 프로그래밍에서는 실제적으로 사용되지는 않지만,
 *        인터넷 홈페이지를 개발하는 웹 프로그래밍에서는 실제로 빈번히 사용되는 기법이므로 그 원리를 이해할 필요가 있다.  
 *    
 */
public class Ex4_05_1_ScoresAverage_GeneratingProgram {
	static final int NOOFSTUDENTS = 10000;  // ***** 총 학생수를 저장하는 상수변수로  이 변수의 값을 바꾸면 점수 개수가 변경됨 ****

	public static void main(String[] args)  {
		System.out.println("/*");
		System.out.println(" *  학생 " + NOOFSTUDENTS + "명의 Java 중간고사 점수를 입력하여 평균과 평균 이상인 점수의 학생 수 구하기");
		System.out.println(" *");  
		System.out.println(" *   스타일 1: 반복문 사용하지 않고서 작성하기");
		System.out.println(" *   이 프로그램은 프로그램 생성 프로그램인 Ex4_8_5_ScoresAverage_GeneratingProgram.java을 통해 자동적으로 만들어진 프로그램임");
		System.out.println(" */");

		System.out.println("public class Ex4_5_2_ScoresAverage" + NOOFSTUDENTS + "_AutoGenerated {");
		System.out.println("    static final int NOOFSTUDENTS = " + NOOFSTUDENTS + "; // 총 학생수를 저장하는 상수변수");
		System.out.println();
		System.out.println("    public static void main(String[] args)  {");  // 

		// 이부분에서는 여러 게의 점수를 저장할 변수들을 선언하는 선언문< int score1, score2, ... score50; >을 생성함
		System.out.print("        int ");   
		for (int i = 1; i < NOOFSTUDENTS; i++)  {//  score1, score2, ... , score(NOOFSTUDENTS-1), (점수개수 -1만큼 score 변수들 선언문을 생성)
			System.out.print(" score" + i + ",");
			if (i % 10==0)
				System.out.print("\n            ");
		}
		
		System.out.println(" score" + NOOFSTUDENTS + ";  // 점수들을 저장할 변수들");  // 마지막 score 변수 뒤에는 ','이 아니라 ';'이 와야함
		System.out.println();


		System.out.println("        int sumOfScore = 0;     // 점수 합계를 저장할 변수, 반드시 0으로 초기화해야 함");
		System.out.println();
		System.out.println("        // " + NOOFSTUDENTS + "명의 학생 점수를 입력하고 이를 누적시킴");
		System.out.println();

		System.out.println("        System.out.print(\"\\n\\n  ** " + NOOFSTUDENTS + "명의 학생 점수를 입력하하여 합과 평균 구하기 **\\n\\n\");"); //  < System.out.print("\n\n  **  " + NOOFSTUDENTS + "명의 학생 점수를 입력하하여 합과 평균 구하기 **\n"); > 생성됨
		System.out.println();

		
		for (int i=1; i <= NOOFSTUDENTS; i++) {  // i번째 점수를 읽어 저장하고 합에 누적하는 부분 생성
			System.out.println("        System.out.print(\"  * input score " + i + " > \");"); //  < System.out.print("  * input scorei > "); > 생성됨
			System.out.println("        score" + i + " = SkScanner.getInt();  ");
			System.out.println("        sumOfScore = sumOfScore + score" + i + ";");
			System.out.println();
		}

		System.out.println("        double avgOfScore;              // 점수 평균 저장 변수");
		System.out.println("        avgOfScore = sumOfScore / (double) NOOFSTUDENTS;  // 실수 평균을 구하기 위해 NOOFSTUDENTS를 실수로 나누어야 함");
		System.out.println();

		System.out.println("        int noGTavg = 0;                // 평균보다 높은 점수 학생수 저장 변수");


		for (int i=1; i <= NOOFSTUDENTS; i++) {  // i번째 점수가 평균보다 크면 noGTavg 증가시키는 부분 생성
			System.out.println("        if (score" + i + " >= avgOfScore) noGTavg++;     // " + i + "번째 점수가 평균보다 크면 noGTavg 1 증가시킴 ");
		}

		System.out.println();
		System.out.println("        System.out.println();");
		System.out.println("        System.out.println(\"\\n  ** 학생 점수 현황 **   \\n\");");
		System.out.println("        System.out.println(\"  * 총 학생수 = \" + NOOFSTUDENTS);");
		System.out.println("        System.out.println(\"  * \" + NOOFSTUDENTS + \" 학생 점수 합 = \" + sumOfScore);");
		System.out.println("        System.out.println(\"  * \" + NOOFSTUDENTS + \" 학생 점수 평균 = \" + avgOfScore);");
		System.out.println("        System.out.println(\"  * 평균보다 높은 점수 학생 수 = \" + noGTavg);");
		System.out.println("    }");
		System.out.println("}");
	}
}

/*
 *  [ 실습과제 ]
 *  
 *    o 이 프로그램이 생성한 프로그램은 점수를 입력받아 저장하므로 많은 데이터를 입력해야한다.
 *      점수를 자동적으로 생성하여 저장하는 방법으로 난수를 이용한다.
 *    
 *      Java에서는 난수를 생성하기 위해 java.lang.math 클래스의 random() 메소드를 제공한다.
 *      0부터 100 사이의 정수를 난수로 생성하려면 (int) (java.lang.Math.random() * 101)로 하면 된다.
 *    
 *      에를 들어 int score3 = (int) (java.lang.Math.random() * 101); 로 하면 score3변수에는 0과 100 사이의 정수가 저장된다.
 *    
 *      이 프로그램에서 정수를 입력받지 않고 난수를 생성하여 저장하도록 프로그램을 수정하고 작성된 프로그램을 수핸시켜 보라. 
 *    
 *  
 * [ 스스로 생각하고 고민해볼 과제 ]
 * 
 *     o 직접 Java 프로그램을 작성하는 것과 프로그램 생성 프로그램을 통하여 프로그램을 작성하는 것의 차이점에 대해 생각해 보시오.
 *      
 *   
 */
	