package ex12_more;

/*  [ Print_IlikeJava_GeneratingProgram ]: "I Like Java "를 1221번 출력하는 클래스를 출력하는 프로그램
 * 
 *    o 스타일 3: 반복문 사용하지 않는 프로그램 생성하여 수행하기
 *   
 *     - System.out.print("I Like Java ");> 문장을  원하는 회수만큼 자동 출력하는  프로그램 생성성하기
 *     
 *    o 이 프로그램은 프로그램을 생성하는 프로그램이다. 
 *    
 *      - 프로그램을 생성한다는 것은 "프로그램은 단순히 문자들의 나열"이라는 것을   확인시키는 것이며, 
 *        System.out.println() 메소드에서 Java 클래스를 구성하는  문자들을 출력하면 된다.  
 *    
 *      - 이러한 프로그래밍 기법은 Java 프로그래밍에서는 실제적으로 사용되지는 않지만,
 *        인터넷 홈페이지를 개발하는 웹 프로그래밍에서는 실제로 빈번히 사용되는 기법이므로 그 원리를 이해할 필요가 있다.     
 *      
 *    o 똑같은 작업을 반복하는 프로그램을 반복문을 사용하지 않고서 직접 작성해보는 것은 
 *      반복문의 중요성을 이해하기 위해 매우 중요하다.
 *        
 *    o 반복문을 사용하지 않고서 직접 반복문장을 나열하는 것은 반복 회수에 따라 난이도가 달라진다. 
 *      반복회수가 작을 때는 때에는 대수롭지 않다가, 회수가 많아지면 점점 어려워져 
 *      회수가 아주 많아지면 거의 불가능해 보이기도 한다. 
 *      1221번은 직접 할 수 있으나 12321번, 1234321번 등의 가능할까?
 *       
 *   *****************************************************************************************************************
 *    o 반복문 쓰지 않고 1221번 또는 그 이상을 출력하는 프로그램 작성하기
 *    
 *       -  첫번째 방법: 프로그램 생성 프로그램을 이용하여 < System.out.print("I Like Java ");>을 
 *                   원하는 회수만큼 출력하는 프로그램을 Console 뷰에 출력하고 이를 클래스로  프로그램 완성
 *   
 *      1) Ex4_4_5_Print_IlikeJava1221_AutoGenerated 클래스 생성
 *      2) 이 프로그램의 <<   int cntIlikeJava = 121; >>의 출력회수를 1221로 변경하고 확인
 *      3) 프로그램을 실행하여 console 뷰에 작성된 프로그램 확인
 *      4) console 뷰의 모든 내용을 < 오른쪽 버튼 > -> < Select All >을 이용하여 선택한 후 Ctrl-C 버튼으로 캡쳐
 *      5) Ex4_4_5_Print_IlikeJava1221_AutoGenerated 클래스에  캡처한 내용을 Ctrl-V로 붙여넣기 
 *      6) Ex4_4_5_Print_IlikeJava1221_AutoGenerated 클래스를 저장하고 실행
 *      
 *      질문: < System.out.print("I Like Java ");> 문장을 1221번 출력하기 위해 for 문을 사용한 것 아닌가요?
 *      대답: 주어진 문제는 "I Like Java "를 출력하는 프로그램에서 반복문을 사용하지 말라는 것이고, 
 *            그 프로그램이 "I Like Java "를 정확히 1221번 출력함을 확신해야 한다는 것이다. 
 *            1)부터 7)의 방법으로 만들어진 프로그램은 for 문 등의 반복문이 없고 100% 확실히 정확히 1221번 출력한다  
*   *****************************************************************************************************************
 */

public class Ex4_04_4_Print_IlikeJava_GeneratingProgram {


	public static void main(String[] args)  {
		int cntIlikeJava = 1121;  // ***** 이 변수의 값을 바꾸면 출력 회수가 변경됨 ****
		
		System.out.println("/*");
		System.out.println(" *  \"I Llike java \"를 " + cntIlikeJava  + "번 출력하기");
		System.out.println(" *");  
		System.out.println(" *   스타일 1: 반복문 사용하지 않고서 작성하기");
		System.out.println(" *   이 프로그램은 프로그램 생성 프로그램인 Print_IlikeJava_GeneratingProgram 클래스를 통해 자동적으로 만들어진 프로그램임");
		System.out.println(" */");

		System.out.println();
		System.out.println("public class Ex4_4_5_Print_IlikeJava" + cntIlikeJava  + "_AutoGenerated {");

		System.out.println("    public static void main(String[] args)  {");  // 

        // < System.out.print("I Like Java "); >를 1221번 출력하는 for 문장
		for(int i = 0; i < cntIlikeJava; i++)
			System.out.println("      System.out.print(\"I Like Java \"); //  " + (i+1) +"번째 ");  // "를 출력하기 위해 \"로 문자열 속에 표시해야 함

		System.out.println("    }");  //  }를 출력
		System.out.println("}"); //  }를 출력
	}
}


/*
 *
 *  [ 실습과제 ]
 *  
 *    o 이 프로그램은  cntIlikeJava 변수에 주어진 회수만큼 "I Llike java "를 반복문 없이 직접 한번씩 출력하는 프로그램을 생성한다.
 *    
 *      222번 출력하도록 cntIlikeJava 변수 값을 변경하여 수행하고 Console 뷰의 출력결과를 
 *      복사(Eclipse의 Console 뷰에서  cntl-A 타이핑 한 후 cntl-C 타이핑하면 복사됨)한 후 
 *      Ex4_4_5_Print_IlikeJava222_AutoGenerated.java 파일에 붙여넣기(cntl-v)로  저장한 후  
 *      그 프로그램을 수행시켜 결과를 확인하라.
 *      
 */
