package ex12_more;
/*
 *  학생 100명의 Java 중간고사 점수를 입력하여 평균과 평균 이상인 점수의 학생 수 구하기
 *
 *   스타일 1: 반복문 사용하지 않고서 작성하기
 *   이 프로그램은 프로그램 생성 프로그램인 Ex4_8_5_ScoresAverage_GeneratingProgram.java을 통해 자동적으로 만들어진 프로그램임
 */
public class Ex4_05_2_ScoresAverage100_AutoGenerated {
    static final int NOOFSTUDENTS = 100; // 총 학생수를 저장하는 상수변수

    public static void main(String[] args)  {
        int  score1, score2, score3, score4, score5, score6, score7, score8, score9, score10,
             score11, score12, score13, score14, score15, score16, score17, score18, score19, score20,
             score21, score22, score23, score24, score25, score26, score27, score28, score29, score30,
             score31, score32, score33, score34, score35, score36, score37, score38, score39, score40,
             score41, score42, score43, score44, score45, score46, score47, score48, score49, score50,
             score51, score52, score53, score54, score55, score56, score57, score58, score59, score60,
             score61, score62, score63, score64, score65, score66, score67, score68, score69, score70,
             score71, score72, score73, score74, score75, score76, score77, score78, score79, score80,
             score81, score82, score83, score84, score85, score86, score87, score88, score89, score90,
             score91, score92, score93, score94, score95, score96, score97, score98, score99, score100;  // 점수들을 저장할 변수들

        int sumOfScore = 0;     // 점수 합계를 저장할 변수, 반드시 0으로 초기화해야 함

        // 100명의 학생 점수를 입력하고 이를 누적시킴

        System.out.print("  * input score 1 > ");
        score1 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score1;

        System.out.print("  * input score 2 > ");
        score2 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score2;

        System.out.print("  * input score 3 > ");
        score3 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score3;

        System.out.print("  * input score 4 > ");
        score4 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score4;

        System.out.print("  * input score 5 > ");
        score5 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score5;

        System.out.print("  * input score 6 > ");
        score6 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score6;

        System.out.print("  * input score 7 > ");
        score7 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score7;

        System.out.print("  * input score 8 > ");
        score8 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score8;

        System.out.print("  * input score 9 > ");
        score9 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score9;

        System.out.print("  * input score 10 > ");
        score10 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score10;

        System.out.print("  * input score 11 > ");
        score11 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score11;

        System.out.print("  * input score 12 > ");
        score12 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score12;

        System.out.print("  * input score 13 > ");
        score13 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score13;

        System.out.print("  * input score 14 > ");
        score14 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score14;

        System.out.print("  * input score 15 > ");
        score15 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score15;

        System.out.print("  * input score 16 > ");
        score16 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score16;

        System.out.print("  * input score 17 > ");
        score17 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score17;

        System.out.print("  * input score 18 > ");
        score18 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score18;

        System.out.print("  * input score 19 > ");
        score19 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score19;

        System.out.print("  * input score 20 > ");
        score20 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score20;

        System.out.print("  * input score 21 > ");
        score21 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score21;

        System.out.print("  * input score 22 > ");
        score22 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score22;

        System.out.print("  * input score 23 > ");
        score23 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score23;

        System.out.print("  * input score 24 > ");
        score24 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score24;

        System.out.print("  * input score 25 > ");
        score25 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score25;

        System.out.print("  * input score 26 > ");
        score26 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score26;

        System.out.print("  * input score 27 > ");
        score27 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score27;

        System.out.print("  * input score 28 > ");
        score28 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score28;

        System.out.print("  * input score 29 > ");
        score29 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score29;

        System.out.print("  * input score 30 > ");
        score30 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score30;

        System.out.print("  * input score 31 > ");
        score31 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score31;

        System.out.print("  * input score 32 > ");
        score32 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score32;

        System.out.print("  * input score 33 > ");
        score33 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score33;

        System.out.print("  * input score 34 > ");
        score34 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score34;

        System.out.print("  * input score 35 > ");
        score35 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score35;

        System.out.print("  * input score 36 > ");
        score36 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score36;

        System.out.print("  * input score 37 > ");
        score37 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score37;

        System.out.print("  * input score 38 > ");
        score38 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score38;

        System.out.print("  * input score 39 > ");
        score39 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score39;

        System.out.print("  * input score 40 > ");
        score40 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score40;

        System.out.print("  * input score 41 > ");
        score41 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score41;

        System.out.print("  * input score 42 > ");
        score42 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score42;

        System.out.print("  * input score 43 > ");
        score43 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score43;

        System.out.print("  * input score 44 > ");
        score44 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score44;

        System.out.print("  * input score 45 > ");
        score45 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score45;

        System.out.print("  * input score 46 > ");
        score46 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score46;

        System.out.print("  * input score 47 > ");
        score47 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score47;

        System.out.print("  * input score 48 > ");
        score48 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score48;

        System.out.print("  * input score 49 > ");
        score49 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score49;

        System.out.print("  * input score 50 > ");
        score50 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score50;

        System.out.print("  * input score 51 > ");
        score51 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score51;

        System.out.print("  * input score 52 > ");
        score52 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score52;

        System.out.print("  * input score 53 > ");
        score53 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score53;

        System.out.print("  * input score 54 > ");
        score54 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score54;

        System.out.print("  * input score 55 > ");
        score55 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score55;

        System.out.print("  * input score 56 > ");
        score56 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score56;

        System.out.print("  * input score 57 > ");
        score57 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score57;

        System.out.print("  * input score 58 > ");
        score58 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score58;

        System.out.print("  * input score 59 > ");
        score59 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score59;

        System.out.print("  * input score 60 > ");
        score60 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score60;

        System.out.print("  * input score 61 > ");
        score61 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score61;

        System.out.print("  * input score 62 > ");
        score62 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score62;

        System.out.print("  * input score 63 > ");
        score63 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score63;

        System.out.print("  * input score 64 > ");
        score64 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score64;

        System.out.print("  * input score 65 > ");
        score65 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score65;

        System.out.print("  * input score 66 > ");
        score66 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score66;

        System.out.print("  * input score 67 > ");
        score67 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score67;

        System.out.print("  * input score 68 > ");
        score68 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score68;

        System.out.print("  * input score 69 > ");
        score69 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score69;

        System.out.print("  * input score 70 > ");
        score70 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score70;

        System.out.print("  * input score 71 > ");
        score71 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score71;

        System.out.print("  * input score 72 > ");
        score72 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score72;

        System.out.print("  * input score 73 > ");
        score73 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score73;

        System.out.print("  * input score 74 > ");
        score74 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score74;

        System.out.print("  * input score 75 > ");
        score75 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score75;

        System.out.print("  * input score 76 > ");
        score76 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score76;

        System.out.print("  * input score 77 > ");
        score77 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score77;

        System.out.print("  * input score 78 > ");
        score78 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score78;

        System.out.print("  * input score 79 > ");
        score79 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score79;

        System.out.print("  * input score 80 > ");
        score80 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score80;

        System.out.print("  * input score 81 > ");
        score81 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score81;

        System.out.print("  * input score 82 > ");
        score82 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score82;

        System.out.print("  * input score 83 > ");
        score83 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score83;

        System.out.print("  * input score 84 > ");
        score84 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score84;

        System.out.print("  * input score 85 > ");
        score85 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score85;

        System.out.print("  * input score 86 > ");
        score86 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score86;

        System.out.print("  * input score 87 > ");
        score87 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score87;

        System.out.print("  * input score 88 > ");
        score88 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score88;

        System.out.print("  * input score 89 > ");
        score89 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score89;

        System.out.print("  * input score 90 > ");
        score90 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score90;

        System.out.print("  * input score 91 > ");
        score91 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score91;

        System.out.print("  * input score 92 > ");
        score92 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score92;

        System.out.print("  * input score 93 > ");
        score93 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score93;

        System.out.print("  * input score 94 > ");
        score94 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score94;

        System.out.print("  * input score 95 > ");
        score95 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score95;

        System.out.print("  * input score 96 > ");
        score96 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score96;

        System.out.print("  * input score 97 > ");
        score97 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score97;

        System.out.print("  * input score 98 > ");
        score98 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score98;

        System.out.print("  * input score 99 > ");
        score99 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score99;

        System.out.print("  * input score 100 > ");
        score100 = SkScanner.getInt();  
        sumOfScore = sumOfScore + score100;

        double avgOfScore;              // 점수 평균 저장 변수
        avgOfScore = sumOfScore / (double) NOOFSTUDENTS;  // 실수 평균을 구하기 위해 NOOFSTUDENTS를 실수로 나누어야 함

        int noGTavg = 0;                // 평균 이상인 점수 학생수 저장 변수
        if (score1 > avgOfScore) noGTavg++;     // 1번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score2 > avgOfScore) noGTavg++;     // 2번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score3 > avgOfScore) noGTavg++;     // 3번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score4 > avgOfScore) noGTavg++;     // 4번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score5 > avgOfScore) noGTavg++;     // 5번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score6 > avgOfScore) noGTavg++;     // 6번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score7 > avgOfScore) noGTavg++;     // 7번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score8 > avgOfScore) noGTavg++;     // 8번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score9 > avgOfScore) noGTavg++;     // 9번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score10 > avgOfScore) noGTavg++;     // 10번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score11 > avgOfScore) noGTavg++;     // 11번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score12 > avgOfScore) noGTavg++;     // 12번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score13 > avgOfScore) noGTavg++;     // 13번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score14 > avgOfScore) noGTavg++;     // 14번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score15 > avgOfScore) noGTavg++;     // 15번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score16 > avgOfScore) noGTavg++;     // 16번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score17 > avgOfScore) noGTavg++;     // 17번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score18 > avgOfScore) noGTavg++;     // 18번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score19 > avgOfScore) noGTavg++;     // 19번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score20 > avgOfScore) noGTavg++;     // 20번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score21 > avgOfScore) noGTavg++;     // 21번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score22 > avgOfScore) noGTavg++;     // 22번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score23 > avgOfScore) noGTavg++;     // 23번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score24 > avgOfScore) noGTavg++;     // 24번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score25 > avgOfScore) noGTavg++;     // 25번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score26 > avgOfScore) noGTavg++;     // 26번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score27 > avgOfScore) noGTavg++;     // 27번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score28 > avgOfScore) noGTavg++;     // 28번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score29 > avgOfScore) noGTavg++;     // 29번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score30 > avgOfScore) noGTavg++;     // 30번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score31 > avgOfScore) noGTavg++;     // 31번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score32 > avgOfScore) noGTavg++;     // 32번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score33 > avgOfScore) noGTavg++;     // 33번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score34 > avgOfScore) noGTavg++;     // 34번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score35 > avgOfScore) noGTavg++;     // 35번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score36 > avgOfScore) noGTavg++;     // 36번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score37 > avgOfScore) noGTavg++;     // 37번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score38 > avgOfScore) noGTavg++;     // 38번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score39 > avgOfScore) noGTavg++;     // 39번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score40 > avgOfScore) noGTavg++;     // 40번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score41 > avgOfScore) noGTavg++;     // 41번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score42 > avgOfScore) noGTavg++;     // 42번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score43 > avgOfScore) noGTavg++;     // 43번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score44 > avgOfScore) noGTavg++;     // 44번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score45 > avgOfScore) noGTavg++;     // 45번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score46 > avgOfScore) noGTavg++;     // 46번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score47 > avgOfScore) noGTavg++;     // 47번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score48 > avgOfScore) noGTavg++;     // 48번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score49 > avgOfScore) noGTavg++;     // 49번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score50 > avgOfScore) noGTavg++;     // 50번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score51 > avgOfScore) noGTavg++;     // 51번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score52 > avgOfScore) noGTavg++;     // 52번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score53 > avgOfScore) noGTavg++;     // 53번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score54 > avgOfScore) noGTavg++;     // 54번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score55 > avgOfScore) noGTavg++;     // 55번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score56 > avgOfScore) noGTavg++;     // 56번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score57 > avgOfScore) noGTavg++;     // 57번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score58 > avgOfScore) noGTavg++;     // 58번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score59 > avgOfScore) noGTavg++;     // 59번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score60 > avgOfScore) noGTavg++;     // 60번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score61 > avgOfScore) noGTavg++;     // 61번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score62 > avgOfScore) noGTavg++;     // 62번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score63 > avgOfScore) noGTavg++;     // 63번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score64 > avgOfScore) noGTavg++;     // 64번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score65 > avgOfScore) noGTavg++;     // 65번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score66 > avgOfScore) noGTavg++;     // 66번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score67 > avgOfScore) noGTavg++;     // 67번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score68 > avgOfScore) noGTavg++;     // 68번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score69 > avgOfScore) noGTavg++;     // 69번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score70 > avgOfScore) noGTavg++;     // 70번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score71 > avgOfScore) noGTavg++;     // 71번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score72 > avgOfScore) noGTavg++;     // 72번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score73 > avgOfScore) noGTavg++;     // 73번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score74 > avgOfScore) noGTavg++;     // 74번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score75 > avgOfScore) noGTavg++;     // 75번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score76 > avgOfScore) noGTavg++;     // 76번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score77 > avgOfScore) noGTavg++;     // 77번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score78 > avgOfScore) noGTavg++;     // 78번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score79 > avgOfScore) noGTavg++;     // 79번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score80 > avgOfScore) noGTavg++;     // 80번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score81 > avgOfScore) noGTavg++;     // 81번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score82 > avgOfScore) noGTavg++;     // 82번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score83 > avgOfScore) noGTavg++;     // 83번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score84 > avgOfScore) noGTavg++;     // 84번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score85 > avgOfScore) noGTavg++;     // 85번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score86 > avgOfScore) noGTavg++;     // 86번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score87 > avgOfScore) noGTavg++;     // 87번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score88 > avgOfScore) noGTavg++;     // 88번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score89 > avgOfScore) noGTavg++;     // 89번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score90 > avgOfScore) noGTavg++;     // 90번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score91 > avgOfScore) noGTavg++;     // 91번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score92 > avgOfScore) noGTavg++;     // 92번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score93 > avgOfScore) noGTavg++;     // 93번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score94 > avgOfScore) noGTavg++;     // 94번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score95 > avgOfScore) noGTavg++;     // 95번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score96 > avgOfScore) noGTavg++;     // 96번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score97 > avgOfScore) noGTavg++;     // 97번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score98 > avgOfScore) noGTavg++;     // 98번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score99 > avgOfScore) noGTavg++;     // 99번째 점수가 평균보다 크면 noGTavg 1 증가시킴 
        if (score100 > avgOfScore) noGTavg++;     // 100번째 점수가 평균보다 크면 noGTavg 1 증가시킴 

        System.out.println();
        System.out.println("**** 학생 점수 현황 ****   ");
        System.out.println("   총 학생수 = " + NOOFSTUDENTS);
        System.out.println("   " + NOOFSTUDENTS + " 학생 점수 합 = " + sumOfScore);
        System.out.println("   " + NOOFSTUDENTS + " 학생 점수 평균 = " + avgOfScore);
        System.out.println("   평균 이상인 점수 학생 수 = " + noGTavg);
    }
}
